import Foundation
import FDBIndexing

/// Model protocol - FDB-independent model interface
///
/// This protocol defines the metadata and serialization interface for data models.
/// It is FDB-independent and can be used in both client (iOS/macOS) and server environments.
///
/// **Implementation**: Generated by @Model macro
///
/// **Usage**:
/// ```swift
/// @Model
/// struct User {
///     #PrimaryKey<User>([\.userID])
///     #Index<User>([\.email])
///
///     var userID: Int64
///     var email: String
///     var name: String
/// }
/// ```
///
/// **Supported Layers**:
/// - RecordLayer (RDB): Uses #PrimaryKey for relational model
/// - DocumentLayer (DocumentDB): No #PrimaryKey, auto-generates ObjectID
/// - GraphLayer (GraphDB): Defines nodes with relationships
public protocol Model: Sendable, Codable {
    // MARK: - Metadata (FDB-independent)

    /// Model type name (e.g., "User")
    static var modelName: String { get }

    /// All field names in the model
    static var allFields: [String] { get }

    /// Index descriptors for this model type
    static var indexDescriptors: [IndexDescriptor] { get }

    /// Get field number for a field name (for Protobuf serialization)
    ///
    /// - Parameter fieldName: The field name
    /// - Returns: Field number, or nil if field doesn't exist
    static func fieldNumber(for fieldName: String) -> Int?

    /// Get enum metadata for a field (if the field is an enum)
    ///
    /// - Parameter fieldName: The field name
    /// - Returns: EnumMetadata if field is an enum, nil otherwise
    static func enumMetadata(for fieldName: String) -> EnumMetadata?
}

// MARK: - Default Implementations

public extension Model {
    /// Default implementation returns empty array
    static var indexDescriptors: [IndexDescriptor] { [] }

    /// Default implementation returns nil (no field numbers)
    static func fieldNumber(for fieldName: String) -> Int? { nil }

    /// Default implementation returns nil (no enum metadata)
    static func enumMetadata(for fieldName: String) -> EnumMetadata? { nil }
}

// MARK: - Backward Compatibility

/// Type alias for backward compatibility
@available(*, deprecated, renamed: "Model")
public typealias Recordable = Model
