import Testing
import Foundation
@testable import FDBModel

/// Tests for @Persistable macro validation and edge cases
@Suite("@Persistable Macro Validation Tests")
struct ModelMacroValidationTests {

    /// Test that indexDescriptors are correctly ordered
    @Test("Index descriptors maintain definition order")
    func indexDescriptorsOrder() {
        // Verify that indexes are in the order they were defined
        #expect(OrderedIndexProduct.indexDescriptors.count == 3)
        #expect(OrderedIndexProduct.indexDescriptors[0].name == "OrderedIndexProduct_category")
        #expect(OrderedIndexProduct.indexDescriptors[1].name == "OrderedIndexProduct_price")
        #expect(OrderedIndexProduct.indexDescriptors[2].name == "OrderedIndexProduct_name")
    }

    /// Test that field numbers are stable
    @Test("Field numbers should be deterministic")
    func fieldNumbersStable() {
        // Field numbers should match field declaration order (id first if auto-generated)
        #expect(StableFieldUser.fieldNumber(for: "id") == 1)
        #expect(StableFieldUser.fieldNumber(for: "email") == 2)
        #expect(StableFieldUser.fieldNumber(for: "name") == 3)
        #expect(StableFieldUser.fieldNumber(for: "createdAt") == 4)
    }

    /// Test that auto-generated id works correctly
    @Test("Auto-generated id")
    func autoGeneratedId() {
        // SimpleUser has auto-generated id
        let user = SimpleUser(email: "test@example.com")

        // Verify id is auto-generated (ULID format: 26 characters)
        #expect(user.id.count == 26)
        #expect(!user.id.isEmpty)

        // Verify metadata
        #expect(SimpleUser.persistableType == "SimpleUser")
        #expect(SimpleUser.allFields.first == "id")
    }

    /// Test IndexKind types can be created
    @Test("IndexKind types can be instantiated")
    func indexKindInstantiation() throws {
        // Verify that all built-in IndexKinds can be created
        _ = ScalarIndexKind()
        _ = CountIndexKind()
        _ = SumIndexKind()
        _ = MinIndexKind()
        _ = MaxIndexKind()
        _ = VersionIndexKind()

        // All should succeed without throwing
    }

    /// Test @Persistable with custom type parameter
    @Test("@Persistable type parameter")
    func persistableTypeParameter() {
        // CustomTypeMember uses @Persistable(type: "CustomUser")
        #expect(CustomTypeMember.persistableType == "CustomUser")
    }

    /// Test user-defined id is preserved
    @Test("User-defined id is preserved")
    func userDefinedIdPreserved() {
        // UserDefinedIdModel has user-defined id with auto-generated default
        let model = UserDefinedIdModel(name: "Test")

        #expect(model.id > 0)  // Auto-generated timestamp-based id
        #expect(UserDefinedIdModel.allFields.contains("id"))
    }
}

// MARK: - Test Structs

@Persistable
struct OrderedIndexProduct {
    #Index<OrderedIndexProduct>([\.category], type: ScalarIndexKind())
    #Index<OrderedIndexProduct>([\.price], type: ScalarIndexKind())
    #Index<OrderedIndexProduct>([\.name], type: ScalarIndexKind())

    var category: String
    var price: Double
    var name: String
}

@Persistable
struct StableFieldUser {
    var email: String
    var name: String
    var createdAt: Date
}

@Persistable
struct SimpleUser {
    var email: String
}

@Persistable(type: "CustomUser")
struct CustomTypeMember {
    var name: String
}

@Persistable
struct UserDefinedIdModel {
    var id: Int64 = Int64(Date().timeIntervalSince1970 * 1000)  // User-defined id with default
    var name: String
}
