// VersionIndexKind.swift
// FDBIndexing - VERSION (Optimistic Concurrency Control) index kind
//
// Provides record versioning and OCC (Optimistic Concurrency Control).
// Uses FoundationDB's versionstamp feature to automatically generate
// monotonically increasing unique values.

import Foundation

/// VERSION (Optimistic Concurrency Control) index kind
///
/// **Purpose**: Record versioning and OCC
/// - Uses FoundationDB's versionstamp
/// - Automatically generates monotonically increasing unique values
/// - Detects concurrent edits by multiple users
///
/// **Subspace structure**: flat
/// - Key: `[indexSubspace][primaryKey][versionstamp] = timestamp`
/// - versionstamp: FDB-generated 10-byte unique value
/// - timestamp: Timestamp when record was created
///
/// **Supported types**:
/// - Special field name: `"_version"` (not an actual record field)
/// - No type check (versionstamp is auto-generated by FDB)
///
/// **Example**:
/// ```swift
/// // Version index (manual creation)
/// let versionIndex = IndexDescriptor(
///     name: "Document_version_index",
///     keyPaths: ["_version"],  // Special field name
///     kind: try! IndexKind(VersionIndexKind()),
///     commonOptions: .init()
/// )
///
/// // Note: Not directly supported by #Index macro
/// // Must be manually added to Schema
/// let schema = Schema([Document.self], indexes: [versionIndex])
/// ```
///
/// **OCC usage example**:
/// ```swift
/// // 1. Get current version
/// let currentVersion = try await versionIndex.getCurrentVersion(
///     primaryKey: Tuple(document.documentID),
///     transaction: transaction
/// )
///
/// // 2. Update record
/// document.title = "New Title"
/// try await store.save(document)
///
/// // 3. Check version (conflict detection)
/// try await versionIndex.checkVersion(
///     primaryKey: Tuple(document.documentID),
///     expectedVersion: currentVersion,
///     transaction: transaction
/// )
/// // → Throws error if another transaction updated the record
/// ```
public struct VersionIndexKind: IndexKindProtocol {
    /// Kind identifier (built-in kinds use lowercase words)
    public static let identifier = "version"

    /// Subspace structure: Flat (ordered keys)
    ///
    /// **Reason**: VERSION index stores ordered version history
    /// - `[indexSubspace][pk][versionstamp] = timestamp`
    /// - versionstamp is monotonically increasing
    /// - Latest version = last key
    public static let subspaceStructure = SubspaceStructure.flat

    /// Type validation: Only allow special field name `"_version"`
    ///
    /// **Validation**:
    /// - Field count: 1 only
    /// - Field name: `"_version"` (not an actual record field)
    /// - No type check (versionstamp is auto-generated by FDB)
    ///
    /// **Note**: This method is not actually used for type validation
    /// - Version index has no actual record field
    /// - `"_version"` is a special field name (marker)
    /// - Execution layer (IndexManager) handles it appropriately
    ///
    /// **Examples**:
    /// ```swift
    /// // OK: Any type (not actually used)
    /// try VersionIndexKind.validateTypes([Int.self])
    /// try VersionIndexKind.validateTypes([String.self])
    ///
    /// // NG: Multiple fields
    /// try VersionIndexKind.validateTypes([Int.self, String.self])  // throws
    /// ```
    ///
    /// - Parameter types: Array of field types (usually empty or 1)
    /// - Throws: IndexTypeValidationError.invalidTypeCount
    public static func validateTypes(_ types: [Any.Type]) throws {
        // Version index has only one field ("_version")
        // However, this field is not an actual record field,
        // but a special marker representing versionstamp
        guard types.count == 1 else {
            throw IndexTypeValidationError.invalidTypeCount(
                index: identifier,
                expected: 1,
                actual: types.count
            )
        }

        // No type check: versionstamp is auto-generated by FDB
        // Execution layer (IndexManager) treats "_version" field specially
    }

    /// Standard initializer
    ///
    /// **Example**:
    /// ```swift
    /// let kind = try IndexKind(VersionIndexKind())
    /// ```
    public init() {}
}
